[TTS]
"Sound Output" = "default"
"Ignore Replies" = true
"Ignore Emojis" = true
"TTS Blacklist" = []

["Sound Effects"]
"Sound Output" = "default"
Sounds = []

[TTS.Limits]
"Max Word Count" = 100
"Max Word Length" = 15

[TTS."Voice Overrides"]
mercybot77 = "matthew"

[TTS."Regex Replacements"]
"^[\\? ]+$" = "huh?"

[TTS."Word Replacements"]
im = "I'm"
theres = "there's"
tho = "though"
welp = "whelp"
ik = "I know"
ew = "eww"
uwu = "oo woo"
sus = "suss"
